[package]
name = "indypool"
version = "0.1.0"
authors = ["Lim Afriyadi <lim.afriyadi.id@gmail.com>"]

[dependencies]
indy = "1.8.2"
tokio = "0.1"
tokio-core = "0.1"
futures = "0.1"
log = "0.4.1"
serde = { version="^1.0", features=["derive"] }
serde_json ="1.0"
